import "./globals.css";
import 'boxicons/css/boxicons.min.css';


export const metadata = {
  title: "Arabic Technology",
  description: "Generated by DZERO by NULL",
};

export default function RootLayout({ children }) {
    return (
    <html lang="en">
      <body className="bg-[#fcf8ed] text-black transition-colors duration-300 overflow-hidden h-screen">
        {children}
      </body>
    </html>
  );
}
